services:
  siqu.cms_api.event_listener.request.accept_language:
    class: Siqu\CMS\API\EventListener\AcceptLanguageListener
    public: false
    tags:
    - { name: 'kernel.event_listener', event: 'kernel.request', priority: 15 }
  siqu.cms_api.event_listener.request.accept:
    class: Siqu\CMS\API\EventListener\AcceptListener
    public: false
    tags:
    - { name: 'kernel.event_listener', event: 'kernel.request', priority: 17 }
  siqu.cms_api.event_listener.request.listener_attributes:
    class: Siqu\CMS\API\EventListener\RequestAttributeListener
    public: false
    tags:
    - { name: 'kernel.event_listener', event: 'kernel.request', priority: 18 }
  siqu.cms_api.event_listener.response.api_formatter:
    class: Siqu\CMS\API\EventListener\APIResponseListener
    arguments:
    - '@serializer'
    public: false
    tags:
    - { name: 'kernel.event_listener', event: 'kernel.response', priority: 18 }
  siqu.cms_api.event_listener.exception.api:
    class: Siqu\CMS\API\EventListener\APIExceptionListener
    public: false
    tags:
    - { name: 'kernel.event_listener', event: 'kernel.exception', priority: 18 }