services:
  siqu.cms_api.normalizer.object.entity:
    class: Siqu\CMS\API\Normalizer\EntityNormalizer
    public: false
    arguments:
    - '@doctrine.orm.entity_manager'
    - '@serializer.mapping.class_metadata_factory'
    - null
    - '@serializer.property_accessor'
    - '@property_info'
    tags:
    - { name: 'serializer.normalizer' }