image: php:7.2

stages:
- test
- quality
- deploy

cache:
  paths:
  - vendor/

test:
  stage: test
  allow_failure: true
  script:
    - apt-get update -yqq
    - apt-get install git -yqq
    - apt-get install -yqq zlib1g-dev
    - pecl install xdebug
    - docker-php-ext-install zip
    - docker-php-ext-enable xdebug
    - docker-php-ext-enable zip
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - echo "Setting up test database"
    - bin/console doctrine:database:create --env=test
    - bin/console doctrine:schema:update --force --env=test --complete
    - bin/phpunit --colors=never
  artifacts:
    paths:
    - doc/coverage

phpmetrics_quality:
  stage: quality
  allow_failure: true
  script:
    - apt-get update -yqq
    - apt-get install git -yqq
    - apt-get install -yqq zlib1g-dev
    - pecl install xdebug
    - docker-php-ext-install zip
    - docker-php-ext-enable xdebug
    - docker-php-ext-enable zip
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - vendor/phpmetrics/phpmetrics/bin/phpmetrics --report-html=doc/metrics --exclude=bin,vendor,var,Tests --junit=./doc/coverage/logs/junit.xml .
  artifacts:
    paths:
    - doc/metrics

phpcs_quality:
  stage: quality
  allow_failure: true
  script:
    - apt-get update -yqq
    - apt-get install git -yqq
    - apt-get install -yqq zlib1g-dev
    - pecl install xdebug
    - docker-php-ext-install zip
    - docker-php-ext-enable xdebug
    - docker-php-ext-enable zip
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - mkdir doc/phpcs
    - vendor/squizlabs/php_codesniffer/bin/phpcs src/ --report-junit=doc/phpcs/junit.xml --report-info=doc/phpcs/info.txt --report-source
  artifacts:
    paths:
    - doc/phpcs

pages:
  stage: deploy
  script:
  - mv doc/ public/
  artifacts:
    paths:
    - public
    expire_in:
  only:
  - master