image: php:7.2

cache:
  paths:
  - vendor/

before_script:
- apt-get update -yqq
- apt-get install git -yqq
- apt-get install -yqq zlib1g-dev
- pecl install xdebug
- docker-php-ext-enable xdebug
- docker-php-ext-enable zip
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install

test:project:
  script:
    - bin/phpunit