image: php:7.2

cache:
  paths:
  - vendor/

before_script:
- apt-get update -yqq
- apt-get install git -yqq
- apt-get install -yqq zlib1g-dev
- pecl install xdebug
- docker-php-ext-install zip
- docker-php-ext-enable xdebug
- docker-php-ext-enable zip
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install
- echo "Setting up test database"
- bin/console doctrine:database:create --env=test
- bin/console doctrine:schema:update --force --env=test --complete
- bin/console doctrine:fixtures:load --env=test --no-interaction

test:project:
  script:
    - bin/phpunit --colors=never