image: php:7.2

cache:
  paths:
  - vendor/

before_script:
- apt-get update -yqq
- apt-get install git -yqq
- apt-get install -yqq zlib1g-dev
- pecl install xdebug
- docker-php-ext-install zip
- docker-php-ext-enable xdebug
- docker-php-ext-enable zip
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install
- echo "Setting up test database"
- bin/console doctrine:database:create --env=test
- bin/console doctrine:schema:update --force --env=test --complete

test:
  stage: test
  script:
    - bin/phpunit --colors=never
  artifacts:
    paths:
    - doc/coverage

quality:
  stage: quality
  script:
    - vendor/phpmetrics/phpmetrics/bin/phpmetrics --report-html=doc/metrics --exclude=bin,vendor,var,Tests --junit=./doc/coverage/logs/junit.xml .
  artifacts:
    paths:
    - doc/metrics

pages:
  stage: deploy
  script:
  - mv doc/ public/
  artifacts:
    paths:
    - public
    expire_in:
  only:
  - master