image: php:7.2

stages:
- test
- quality
- deploy

cache:
  paths:
  - vendor/

before_script:
- apt-get update -yqq
- apt-get install git -yqq
- apt-get install -yqq zlib1g-dev
- pecl install xdebug
- docker-php-ext-install zip
- docker-php-ext-enable xdebug
- docker-php-ext-enable zip
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install
- echo "Setting up test database"
- bin/console doctrine:database:create --env=test
- bin/console doctrine:schema:update --force --env=test --complete

test:
  stage: test
  script:
    - bin/phpunit --colors=never
  artifacts:
    paths:
    - doc/coverage

phpmetrics_quality:
  stage: quality
  script:
    - vendor/phpmetrics/phpmetrics/bin/phpmetrics --report-html=doc/metrics --exclude=bin,vendor,var,Tests --junit=./doc/coverage/logs/junit.xml .
  artifacts:
    paths:
    - doc/metrics

code_quality:
  stage: quality
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable_dind
  script:
  - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
  - docker run
    --env SOURCE_CODE="$PWD"
    --volume "$PWD":/code
    --volume /var/run/docker.sock:/var/run/docker.sock
    "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /src
  artifacts:
    reports:
      codequality: [gl-code-quality-report.json]

pages:
  stage: deploy
  script:
  - mv doc/ public/
  artifacts:
    paths:
    - public
    expire_in:
  only:
  - master