controllers:
  resource: ../../src/API/Controller/
  prefix: /api/v1
  type: annotation
  defaults:
    listener:
      request:
        accept-language: true
        accept: true
        response-formatter: true
        api-exception: true