services:
  siqu.cms_core.doctrine.listener.cms_user:
    class: Siqu\CMS\Core\Doctrine\Listener\CMSUserListener
    public: false
    arguments:
    - '@siqu.cms_core.util.password_updater'
    - '@siqu.cms_core.util.uuid_generator'
    tags:
    - { name: 'doctrine.event_subscriber' }
  siqu.cms_core.doctrine.listener.blameable:
    class: Siqu\CMS\Core\Doctrine\Listener\BlameableListener
    public: false
    arguments:
    - '@security.token_storage'
    tags:
    - { name: 'doctrine.event_subscriber' }
  siqu.cms_core.doctrine.listener.timestampable:
    class: Siqu\CMS\Core\Doctrine\Listener\TimestampableListener
    public: false
    tags:
    - { name: 'doctrine.event_subscriber' }
  siqu.cms_core.doctrine.listener.identifiable:
    class: Siqu\CMS\Core\Doctrine\Listener\IdentifiableListener
    public: false
    arguments:
    - '@siqu.cms_core.util.uuid_generator'
    tags:
    - { name: 'doctrine.event_subscriber' }
  siqu.cms_core.doctrine.listener.page:
    class: Siqu\CMS\Core\Doctrine\Listener\PageListener
    public: false
    arguments:
    - '@siqu.cms_core.util.urlizer'
    tags:
    - { name: 'doctrine.event_subscriber' }
  siqu.cms_core.util.password_updater:
    class: Siqu\CMS\Core\Util\PasswordUpdater
    public: false
    arguments:
    - '@security.encoder_factory'
  siqu.cms_core.util.uuid_generator:
    class: Siqu\CMS\Core\Util\UuidGenerator
    public: false
  siqu.cms_core.util.urlizer:
    class: Siqu\CMS\Core\Util\Urlizer
    public: false