services:
  siqu.cms_core.doctrine.listener.cms_user_listener:
    class: Siqu\CMS\Core\Doctrine\Listener\CMSUserListener
    public: false
    arguments:
      - '@siqu.cms_core.util.password_updater'
      - '@siqu.cms_core.util.uuid_generator'
    tags:
      - { name: 'doctrine.event_subscriber' }
  siqu.cms_core.util.password_updater:
    class: Siqu\CMS\Core\Util\PasswordUpdater
    public: false
    arguments:
      - '@security.encoder_factory'
  siqu.cms_core.util.uuid_generator:
    class: Siqu\CMS\Core\Util\UuidGenerator
    public: false